# Generated by Django 2.1.3 on 2019-05-31 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfood',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
