# Generated by Django 2.1.3 on 2019-05-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lunch_lunchreservation_roomamenity_roomamenityreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='desc',
            field=models.CharField(default='', max_length=100),
        ),
    ]
