# Generated by Django 2.1.3 on 2019-05-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190512_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=100, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='user',
            name='hotel_name',
            field=models.CharField(default='', max_length=100, verbose_name='hotel_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='name'),
        ),
    ]
