# Generated by Django 2.0 on 2019-05-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_onlyoncecredit_userscan'),
        ('core', '0005_auto_20190520_0921'),
    ]

    operations = [
    ]
