# Generated by Django 2.1.3 on 2019-05-31 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_teabreak'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Food')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='qrcode',
            field=models.ImageField(default='', upload_to='user/qrcode'),
        ),
        migrations.AddField(
            model_name='userfood',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
    ]
